### ISSUE TITLE
Problem with AutoSizer in v9.21.1

### ISSUE THREAD

**Issue by ashmigelski** [bvaughn/react-virtualized#1378]
Hey

In my app I have tabs with virtualized lists on it. I use `scrollTop` property to restore scroll position when switching tabs. After update to 9.21.1 I faced strange bug (in 9.21.0 same code works fine)

### What is the current behavior?
![react-virtualized](https://user-images.githubusercontent.com/4904519/58417423-697c2b00-808d-11e9-9bb0-3b65b8f16dd7.gif)

### Steps to reproduce
1) scroll List1 on *Tab 1*
2) go to *Tab 2*
3) scroll List2 on *Tab 2*
4) back to *Tab 1* (`List with AutoSizer`) -> *BUG*: blank list. List will be shown if scroll
5) back to *Tab 2* (`List without Autosizer`) -> works as needed (restore previous scrollTop)

Code https://codesandbox.io/s/reactvirtualized9211-two-tabs-with-scrolltop-w5vpd

### Which versions of React and react-virtualized, and which browser / OS are affected by this issue? Did this work in previous versions of react-virtualized?
|                   |          |
|-------------------|----------|
| Browser           |    Chrome   70   |
| OS                |   Debian       |
| React             |    16.8.6     |
| React DOM         | 16.8.6      |
| react-virtualized |   9.21.1       |

**Comment by gsbelarus** [comment]
I have the same bug with **Grid** component. Forced to rollback to version 9.21.0 that works fine. If you set initial **ScrollTo** value greater than zero then part of the **Grid** will be drawn blank on first render.

**Comment by gsbelarus** [comment]
I think the problem is with this commit: https://github.com/bvaughn/react-virtualized/commit/32855b8abfc0980237970e148fc625edc78f7e01

**Comment by cquiroz** [comment]
I see this same issue as result of a first call from AutoSizer with width 0
I've fixed it by passing a
`width = max(1, size.width)`
to the table

**Comment by Kyle-Lowe** [comment]
@cquiroz where exactly are you getting `size` from?  The only props available in the child function of autosizer are width and height.  Additionally, I assume max is shorthand for Math.max.  In which case I attempted to set the width property of the Table to `Math.max(1, width)` and am experiencing the same issue.  I agree with @gsbelarus that this may be a side effect of the fix to grid in the most recent commit.

**Comment by Kyle-Lowe** [comment]
Has anyone had any additional luck with finding a version of react-virtualized where the scrollTo prop for Tables is actually reflected and accurate upon render?

**Comment by cquiroz** [comment]
Actually what is working form is to check `size.width/height`. If it is 0 I render a dummy div, if more than zero then I render the `Table` and `scrollTop` works fine. Likely if you render with 0 the internal state gets messed up

**Comment by Kyle-Lowe** [comment]
So, you are using the latest `9.21.1` and prior to setting `scrollTop` on your table you are interrogating the size of what exactly?  I don't think your solution pertains to the initial issue found by @ashmigelski.  When interrogating my preserved `scrollTop` position for zero and only passing it if > 0 I am still seeing the issue @ashmigelski noted in the initial post where the scroll position is always defaulted to zero and we see empty space where rows that are not currently part of the rendered view should exist.  Anytime the Table is unmounted and then mounted with a new `scrollTop`, this issue occurs.

**Comment by Kyle-Lowe** [comment]
@ashmigelski, I have reverted back to version `9.20.0` in the project I'm currently working on and also updated your code sandbox to this version.  This appears to have fixed the syncing issue between the AutoSizer and Table components.  If you are looking for a temporary solution until the issue can be resolved going forward this may help you out.

**Comment by pierre-aurele-martin** [comment]
Hello, I confirm this issue ! Took me a while to understand that it was not my fault ;)

The "hack" I've found is instead of returning a width=0 from calcColumnWidth, I return 0.1 - in my context, it doesn't do a difference.

**Comment by saisandeepvaddi** [comment]
Yes, I had the similar issue. Reverting to `9.19.1` fixed it.

**Comment by Z-HNAN** [comment]
try this
```jsx
<HeaderGrid
    cellRenderer={(params) => {
        return this.cellRender(params);
    }}
     ......
 />
```
