### ISSUE TITLE
MultiGrid alignment when scrolled to far-right or bottom

### ISSUE THREAD

**Issue by andrewdavey** [bvaughn/react-virtualized#535]
I was trying out the MultiGrid demo at https://bvaughn.github.io/react-virtualized/#/components/MultiGrid and noticed a problem when scrolling to the far-right or bottom.

![multi-grid-alignment](https://cloud.githubusercontent.com/assets/292014/21841591/bc838464-d7da-11e6-94e5-f7b67a781f7b.png)

The columns in the top grid become misaligned with the main grid body. (Same for the rows when scrolling to bottom.)

I assume this is due to the presence of the scrollbar in one div causing an offset?

Tested in Chrome 55 and Firefox 50

**Comment by natew** [comment]
I noticed this as well, with a pretty wide table (10k items by 70px), it actually seems to distort more or less based on scroll:

![image](https://cloud.githubusercontent.com/assets/12100/22135243/dccc7142-de81-11e6-942b-f9d47acf3224.png)

Direction seems to affect it as well:

https://v.usetapes.com/Qg5Mlwx5Dr

**Comment by jeffvan576** [comment]
Running into the same issue using ScrollSync

![image](https://cloud.githubusercontent.com/assets/7004952/22219733/f5f46f62-e179-11e6-83e7-c9c9d0349374.png)

**Comment by bvaughn** [comment]
Makes sense; `MultiGrid` uses `ScrollSync` internally, unfortunately.

**Comment by kachkaev** [comment]
Has anyone been able to find a temporary workaround for this by a chance? It'd be great if you shared.

**Comment by jeffvan576** [comment]
It's not pretty but it's a workaround:

`<AutoSizer>
  {({ width, height }) => {
  const adjustedMeasurement = this.adjusted(width, height);
`

`
adjusted(width, height) {
    const {
      columnWidth,
      columnCount,
      rowHeight,
      rowCount,
    } = this.state;

    const totalGridWidth = columnWidth * columnCount;
    const totalGridHeight = rowHeight * rowCount;
    const widthTest = totalGridWidth > width;
    const heightTest = totalGridHeight > height && widthTest;

    return {
      width: widthTest ? width - scrollbarSize() : width,
      height: heightTest ? height - scrollbarSize() : height,
    };
  }
`

Make sure to import scrollbarSize:

`import scrollbarSize from 'dom-helpers/util/scrollbarSize';`

Then feed in adjustedMeasurement.height and adjustedMeasurement.width instead of the AutoSizer width and height. Seems to be working here so far. Again, not pretty but a temporary patch.

**Comment by abhishiv** [comment]
Seems because of scrollbars. On chrome I can hide the scrollbars using this css

```
.grid-parent *::-webkit-scrollbar {
    width: 0px;
    height: 0px;
}
```

But for ff, I have to use @jeffvan576 solution. Would be nice to have it fixed in react-virtualized itself.

**Comment by bvaughn** [comment]
Fixed this, although I'm not _super_ thrilled with the fix. Check out 9.2.1 ...

**Comment by neti123** [comment]
Still not fixed.

**Comment by casvil** [comment]
still not fixed

**Comment by SaliaLashgari** [comment]
Just to confirm, this still is not fixed and does not work...

**Comment by jeremysykes** [comment]
I know this issue was opened in 2017 and the issue is marked as closed, but this is still an ongoing issue. A fix for this would be greatly appreciated. thanks.
