### ISSUE TITLE
fast scrolling in InfiniteLoader scrolls back to top after data is loaded

### ISSUE THREAD

**Issue by XeniaSiskaki** [bvaughn/react-virtualized#595]
I am using an `InfiniteLoader` with a `Table` and the problem I'm having is the following: when I move the scrollbar to the end quickly (or an index where data is not yet loaded), it scrolls back to the top after data is loaded. This problem can also be observed in the demo example [here](https://bvaughn.github.io/react-virtualized/#/components/InfiniteLoader)

**Comment by vasyl-romanchak** [comment]
+1

**Comment by bvaughn** [comment]
Ooh, nice bug report.

**Comment by bvaughn** [comment]
Looks like it's not specific to `Table` (which makes sense considering `Table` and `List` both use `Grid` internally). Adding some logging, I see that `Grid` is getting a "scroll" event with `scrollTop:0` for some reason.

**Comment by bvaughn** [comment]
This looks like something introduced by me recently when I added support for the new async `CellMeasurer` to `Grid`. (Sorry!) `recomputeGridSize` is called by `InfiniteLoader` once its new rows load. This in turn sets the `_recomputeScrollTopFlag` flag which causes the chain of methods I mentioned above to be invoked.

This shouldn't matter, since `_updateScrollTopForScrollToRow ` [short-circuits if the user hasn't actually specified a `scrollToRow`](https://github.com/bvaughn/react-virtualized/blob/ebe7666b80bad9d2e80a883b832f239df9f04e93/source/Grid/Grid.js#L994)- or at least it attempts to 😅 but in this case `scrollToRow` is `null` and `null >= 0` is true 🤡.

I have to run to an appointment now but the fix for this is simple. I just want to make sure I added at least one regression test first. I'll get it done sometime this morning/afternoon.

**Comment by bvaughn** [comment]
Fixed in 2176a5f. Will go out in 9.1.0 shortly.

**Comment by XeniaSiskaki** [comment]
Super! Will test it when it's out

**Comment by bvaughn** [comment]
It was released with 9.1.0 yesterday.

**Comment by nicolasletoublon** [comment]
It seems that this is still happening. Using WindowScroller, InfinitedLoader, Autosizer and List

**Comment by vn425282** [comment]
may I know any workaround on it ?

**Comment by HarvWorks** [comment]
@bvaughn I am also facing the same issue with AutoSizer, InfiniteLoader, and List.  It is only happening on fast scrolls.

**Comment by HarvWorks** [comment]
@vn425282 @nicolasletoublon I am guessing you guys don't have a skeleton and are just rendering null in `renderActionRow` when there is nothing to render.
