### ISSUE TITLE
Masonry component re-renders items that are visible in the viewport while scrolling

### ISSUE THREAD

**Issue by danielcardoso5** [bvaughn/react-virtualized#875]
I'm having some performance issues using the Masonry component. Sometimes, when scrolling a page with masonry cells, while they are still visible in the viewport, a re-render is triggered, causing the browser to do a new layout and painting operation for the "new" items, but nothing on them has changed to make them trigger a re-render. This can be seen by using a CSS keyframe animation that's triggered when an element is added to the DOM.
I can also reproduce the issue on the demo page.
To reproduce it I do the following steps:

1. Go here: https://bvaughn.github.io/react-virtualized/#/components/Masonry
2. Select checkbox "Use WindowScroller?"
3. Open Developer Tools
4. Select a masonry brick and change it's corresponding <style> tag by adding the following code 
```
@keyframes fadeIn {
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
}

```
5. Set the following CSS properties for the current masonry brick class: `animation-name: fadeIn; animation-duration: 1s;`
6. Then scroll on the page and watch the cells animating while they are still in the viewport, you can also see in the elements panel the corresponding elements flashing, meaning they were re-rendered. I would expect them to be only rendered when being added to the DOM on scroll at the bottom or top of the page, depending on the direction of the scroll.

**Comment by bvaughn** [comment]
I'm also seeing a flicker, like DOM elements are being re-created, each time one of the Masonry cells is removed from the container.

I'm not sure why this is, off the top of my head. If you'd like to look into it, I'd welcome another hand. 😄

**Comment by bvaughn** [comment]
I think I know why this is! It's due to [`Masonry`'s measure cycle](https://github.com/bvaughn/react-virtualized/blob/34a5f25818a0dadfad7f0a57654fd3cc0330b260/source/Masonry/Masonry.js#L174-L206). This effectively flushes everything but newly-measured cells whenever `Masonry` runs out of measurements. That's not great, because the result is that React removes all of the already-measured DOM elements and then re-creates them later. Instead `Masonry` should append to existing cells.

**Comment by bvaughn** [comment]
I've got a handle on this. Hopefully will release a bug-fix patch soon that drastically reduces this.

**Comment by bvaughn** [comment]
Should be fixed via d561d9c

**Comment by bvaughn** [comment]
Fix will be released with 9.13.0 shortly.

**Comment by danielcardoso5** [comment]
Glad you got this fixed. Let me know if you need any help testing this.

**Comment by bvaughn** [comment]
If you're still using `Masonry`, I'd love to know if the performance issue you reported originally has been resolved in the 9.13 release.

**Comment by danielcardoso5** [comment]
I'm still having this issue with the latest release. Can also reproduce it in the demo page, is the code updated in the demo with the latest release?

**Comment by bvaughn** [comment]
> Can also reproduce it in the demo page

What can you reproduce on the demo page? Could you be much more specific? 😄 

Some amount of repaint flashing is expected, even on the demo page, for the following reasons:
* As new cells are measured, the total (estimated) height of the Masonry view is adjusted which can will cause a small repaint to the container
* As new cells are measured, the amount of gutter/spacing between them occasionally causes Masonry to measure and then remove a cell. This is a limitation of the `Masonry` component not knowing enough about the layout algorithm to avoid sometimes measuring more cells than is strictly necessary.

I'd be open for ideas to improve the things I mentioned above.

**Comment by lrholmes** [comment]
Hi, I'm also having this issue. It's occurring under the same circumstances described in the OP - an opacity/transform animation on a cell item is being re-rendered while scrolling, making the animation unusable.

I wonder if there is a better or recommended way of handling animation on cell enter?
